### ISSUE TITLE
Wrong Readme Steps

### ISSUE THREAD

**Issue by Be55am** [slightlynervousdoggo/elastic-kibana-docker-nginx-letsencrypt#1]
the commands in the readme arent clear and doesn't work

**Comment by juan-vg** [comment]
Since `VERSION` is an env var, this repo could be used to run v6.8 clusters (or any other version). There is no disclaimer about it. 


### For v6.8

- The randomly generated password for Kibana will belong to the user name "kibana" instead of "kibana_system". This should be warned at the README steps, and also it must be modified in the _kib01_ definition (`docker-compose.yml`) at the ELASTICSEARCH_USERNAME env var.

**Comment by juan-vg** [comment]
In order to generate the random passwords the `elasticsearch-setup-passwords` binary requires to trust the ES certs. Step 6 must be modified to handle first the CA addition to the trust set.

```
6. Run the *elasticsearch-generate-passwords* tool on es01 to generate passwords for all built-in users and kibana_system. Make note of these passwords.
    ```
    docker exec es01 /bin/bash -c "ln -s /usr/share/elasticsearch/config/certificates/ca/ca.crt /etc/pki/ca-trust/source/anchors/es-cluster-ca.crt"
    docker exec es01 /bin/bash -c "update-ca-trust"
    docker exec es01 /bin/bash -c "bin/elasticsearch-setup-passwords auto --batch --url https://es01:9200"
    ```
```

**Comment by datallboy** [comment]
> Since `VERSION` is an env var, this repo could be used to run v6.8 clusters (or any other version). There is no disclaimer about it.
> ### For v6.8
> 
>     * The randomly generated password for Kibana will belong to the user name "kibana" instead of "kibana_system". This should be warned at the README steps, and also it must be modified in the _kib01_ definition (`docker-compose.yml`) at the ELASTICSEARCH_USERNAME env var.

Added disclaimer about the version in this commit: https://github.com/datallboy/elastic-kibana-docker-nginx-letsencrypt/commit/7254ff2c6b4eb917fb6786896a793895681027bd

**Comment by datallboy** [comment]
> In order to generate the random passwords the `elasticsearch-setup-passwords` binary requires to trust the ES certs. Step 6 must be modified to handle first the CA addition to the trust set.
> 
> ```
> 6. Run the *elasticsearch-generate-passwords* tool on es01 to generate passwords for all built-in users and kibana_system. Make note of these passwords.
>     ```
>     docker exec es01 /bin/bash -c "ln -s /usr/share/elasticsearch/config/certificates/ca/ca.crt /etc/pki/ca-trust/source/anchors/es-cluster-ca.crt"
>     docker exec es01 /bin/bash -c "update-ca-trust"
>     docker exec es01 /bin/bash -c "bin/elasticsearch-setup-passwords auto --batch --url https://es01:9200"
>     ```
> ```

Added a comment onto  #7 about CA trust store. Base image for Elasticsearch changed to Ubuntu 20.04.
